### ISSUE TITLE
Model Helpers

### ISSUE THREAD

**Issue by pipsie100** [davedawkins/sutil-template-elmish#1]
Where is the m in m.Counter coming from?

**Comment by davedawkins** [comment]
Hi,
Let's rewrite the line where getCounter is used to try and make it clearer:

model |> Store.map getCounter

Is equivalent to

model |> Store.map (fun m -> m.Counter)

So, m is the new instance of Model, and the whole expression is the current value of the model counter.

Does that help? I can elaborate later when I'm at a computer ( on phone right now )
